### ISSUE TITLE
Visual Studio Warning: result of 32-bit shift implicitly converted to 64 bits

### ISSUE THREAD

**Issue by LeMoussel** [sjinks/cpp_isaac64#2]
VS compiler [indeed suspects](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4334?view=vs-2017) that 64-bit was meant:

> isaac64_engine.h(22): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
> isaac32_engine.h(22): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)

The compiler is complaining because the result in a 64 bit variable so it assumes to do a 64 bit shift instead of a 32 bit shift. This can fix that by using :
```
static constexpr std::size_t randsiz(void)  { return 1ULL << isaac32_engine::randsizl(); }
static constexpr std::size_t randsiz(void)  { return 1ULL << isaac64_engine::randsizl(); }
```

**Comment by sjinks** [comment]
Fixed, thank you!
