### ISSUE TITLE
Seed from Sequence not initialized

### ISSUE THREAD

**Issue by vzz3** [sjinks/cpp_isaac64#4]
I perhaps misunderstood the purpose of the method `template<typename Sseq> void seed(Sseq& s)` and the constructor `template<typename sseq> explicit isaac64_engine(sseq& s)` of the class `isaac64_engine` but I think the method `template<typename Sseq> void seed(Sseq& s)` is missing a call for `this->init()` at the end. 

I thought, i could use the `template<typename sseq> explicit isaac64_engine(sseq& s)` with a `std::random_device` in order to produce a secure random number with your library. Please see my simplified example that illustrates what I was trying to do:
```
std::random_device rdev();
isaac64_engine randEngine(rdev);
auto randWord = randEngine();
```
However, without the `init()` in `template<typename Sseq> void seed(Sseq& s)` the `randWord` is the same after every execution of the code. After I added `this->init();` at the end of `<typename Sseq> void seed(Sseq& s)` method it works as I expected it to work.

### my suggested solution:
```
	template<typename Sseq>
	void seed(Sseq& s)
	{
		for (std::size_t i=0; i<randsiz(); ++i) {
			this->m_randrsl[i] = s();
		}
		this->init();
	}
```

**Comment by sjinks** [comment]
Good catch, thank you very much!

**Comment by vzz3** [comment]
You are welcome! Thank your for the super quick response!
